#!/usr/bin/python

# WRITTEN FOR PYTHON VERSION 2.7.5

import socket
import errno
import os
import json
import codecs

DEV = False
ROOT = "/nfs/stak/users/christj/ONIDbot"
DEVROOT = "/nfs/stak/users/christj/ONIDbot_DEV"

# region File IO
def IO_RealPath(filePath):
    return os.path.realpath(os.path.expanduser(filePath))
def IO_ReadFile(filePath, defaultContents=None, binary=False):
    filePath = IO_RealPath(filePath)
    try:
        if binary:
            with open(filePath, "rb") as f:
                return f.read()
        else:
            with codecs.open(filePath, "r", encoding="utf-8") as f:
                return f.read()
    except IOError as ex:
        if ex.args[0] == errno.ENOENT and defaultContents != None:
            return defaultContents
        else:
            raise
    if defaultContents != None and not os.path.exists(filePath):
        return defaultContents
def IO_SerializeJson(obj, compact=False):
    return json.dumps(obj, separators=(',', ':') if compact else None, indent=None if compact else 4)
def IO_DeserializeJson(jsonString):
    return json.loads(jsonString)
# endregion

# region Environment
ENV = None
def ENV_Load():
    global ENV
    env_path = os.path.join(DEVROOT if DEV else ROOT, "environment.json")
    ENV = IO_DeserializeJson(IO_ReadFile(env_path))
# endregion

# TODO Find some way to add logging to this script

def Main():
    code = os.environ.get("QUERY_STRING", "").replace("\n", "").replace("\r", "")
    for hostname in ENV["api_hosts"]:
        sock = None
        sockfile = None
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(1.0) # Host needs to connect within 1 second
            sock.connect((hostname, ENV["api_port"]))
            sock.settimeout(30.0) # Host can have up to 30 seconds to reply once connected
            sock.sendall((code + "\n").encode("utf-8"))
            sockfile = sock.makefile("rb", 0)
            return sockfile.readline(65536).decode("utf-8").rstrip("\n")
        except socket.error as ex:
            if ex.args[0] == errno.ECONNREFUSED:
                continue
            else:
                raise ex
        finally:
            if sockfile:
                sockfile.close()
            if sock:
                sock.close()
    raise Exception("All API servers are down.")

print("Content-Type: application/json")
print("")
try:
    ENV_Load()
    print(Main())
except Exception as ex:
    print(IO_SerializeJson({ "success": False, "message": str(ex) }, compact=True))