#!/usr/bin/python

import socket
import os

PORT = 51185
HOSTNAMES = [
    "flip1.engr.oregonstate.edu",
    "flip2.engr.oregonstate.edu",
    "flip3.engr.oregonstate.edu",
    "flip4.engr.oregonstate.edu"
]
CHARSET = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")
MAXLENGTH = 4096

def Main():
    code = os.environ.get("QUERY_STRING", "")
    if code == "":
        return "{ \"success\": false, \"message\": \"No verification code provided in command line args.\" }"
    if len(code) > MAXLENGTH:
        return "{ \"success\": false, \"message\": \"Verification code is too long.\" }"
    if not set(code).issubset(CHARSET):
        return "{ \"success\": false, \"message\": \"Verification code contains invalid characters.\" }"
    for hostname in HOSTNAMES:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock.settimeout(1.0) # Host needs to connect within 1 second
            sock.connect((hostname, PORT))
            sock.settimeout(60.0) # Host can have up to 60 seconds to reply once connected
            sock.sendall(code.encode("ascii"))
            response = sock.recv(MAXLENGTH).decode("ascii")
            return response
        except:
            continue
        finally:
            sock.close()
    return "{ \"success\": false, \"message\": \"All API servers down! Please DM @finlay_the_berry to report this issue.\" }"

print("Content-Type: text/plain")
print("")
try:
    print(Main())
except Exception as ex:
    print("{ \"success\": false, \"message\": \"" + repr(ex) + "\" }")