#!/usr/bin/python

import socket
import sys
import os

# region Environment
ENV = None
def Env_Load():
    env_path = os.path.join(IO_GetScriptDir(), "environment.json")
    if os.stat(env_path).st_mode != 33152:
        raise Exception("Insecure permissions on environment.json. Try chmod 600 environment.json")
    ENV = IO_DeserializeJson(IO_ReadFile(env_path))
# Env_Load() # TODO
# endregion

def Main():
    print("Content-Type: text/plain")
    print("")
    if len(sys.argv) != 2:
        print("ERROR: Bad arg count.")
        print(sys.argv)
        return
    code = sys.argv[1]
    hosts = [
        "flip4.engr.oregonstate.edu",
        "flip3.engr.oregonstate.edu",
        "flip2.engr.oregonstate.edu",
        "flip1.engr.oregonstate.edu"
    ]
    port = 12345
    for host in hosts:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock.settimeout(1.0) # Host needs to connect within 1 second
            sock.connect((host, port))
            sock.settimeout(60.0) # Host can have up to 60 seconds to reply once connected
            sock.sendall(code.encode("utf-8"))
            response = sock.recv(1024).decode("utf-8")
            print(response)
            return
        except:
            continue
        finally:
            sock.close()
    print("ERROR: All hosts down.")
    return
Main()
